import { expect, test } from './fixtures';
import { FLIGHT_MAPS } from '../src/maps';

test('reports a soft ground landing and resumes flight without a reset', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Start motors' }).click();
  await page.keyboard.down('w');
  await expect.poll(async () => parseFloat(await page.locator('#altitude').innerText()), { intervals: [100] }).toBeGreaterThan(3);
  await page.keyboard.up('w');
  await page.keyboard.down('s');
  await expect(page.locator('#flight-state-label')).toHaveText('SOFT LANDING · GROUND');
  await page.keyboard.up('s');
  await expect(page.locator('#altitude')).toContainText('0.0');
  await expect(page.locator('#toast')).toContainText('Soft landing');
  await expect(page.locator('#landing-feedback')).toContainText('m/s');
  await expect(page.locator('#arm-button')).toContainText('Stop motors');
  await page.screenshot({ path: 'test-results/soft-landing.png', fullPage: true });
  await page.keyboard.down('w');
  await expect.poll(async () => parseFloat(await page.locator('#altitude').innerText()), { intervals: [100] }).toBeGreaterThan(2);
  await page.keyboard.up('w');
  await expect(page.locator('#flight-state-label')).toContainText('IN FLIGHT');
});

test('reports a hard sport descent and resets the landing feedback', async ({ page }) => {
  await page.goto('/');
  await page.locator('#flight-mode').selectOption('sport');
  await page.getByRole('button', { name: 'Start motors' }).click();
  await page.keyboard.down('w');
  await expect.poll(async () => parseFloat(await page.locator('#altitude').innerText()), { intervals: [100] }).toBeGreaterThan(6);
  await page.keyboard.up('w');
  await page.keyboard.down('s');
  await expect(page.locator('#flight-state-label')).toHaveText('HARD LANDING · RESET TO RETRY');
  await page.keyboard.up('s');
  await expect(page.locator('#arm-button')).toContainText('Reset flight');
  await expect(page.locator('#toast')).toContainText('Hard landing');
  await page.screenshot({ path: 'test-results/hard-landing.png', fullPage: true });
  await page.keyboard.press('r');
  await expect(page.locator('#flight-state-label')).toHaveText('READY FOR TAKEOFF');
  await expect(page.locator('#altitude')).toContainText('0.0');
  await expect(page.locator('#arm-button')).toContainText('Start motors');
  await expect(page.locator('#landing-feedback')).not.toContainText('Hard landing');
});

test('lands gently on a NYC rooftop, stops its motors, and takes off again', async ({ page }) => {
  const roof = FLIGHT_MAPS.nyc.buildings.find(building => building.x === -21 && building.z === -21)!.tiers[0];
  const rooftopHeight = roof.base + roof.height;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('combobox', { name: 'Flight map' }).selectOption('nyc');
  await page.getByRole('button', { name: 'Start motors' }).click();
  await page.keyboard.down('w');
  await expect.poll(async () => parseFloat(await page.locator('#altitude').innerText()), { intervals: [100], timeout: process.env.CI ? 45000 : 8000 }).toBeGreaterThan(rooftopHeight + 5);
  await page.keyboard.up('w');
  const initialDistance = parseFloat(await page.locator('#distance').innerText());
  await page.keyboard.down('ArrowUp');
  await page.keyboard.down('ArrowLeft');
  await expect.poll(async () => parseFloat(await page.locator('#distance').innerText()), { intervals: [50] }).toBeGreaterThan(initialDistance + 27);
  await page.keyboard.up('ArrowUp');
  await page.keyboard.up('ArrowLeft');
  await expect.poll(async () => parseFloat(await page.locator('#speed').innerText()), { intervals: [100] }).toBeLessThan(0.2);
  await page.keyboard.down('s');
  await expect(page.locator('#flight-state-label')).toHaveText('SOFT LANDING · ROOFTOP');
  await page.keyboard.up('s');
  await expect(page.locator('#contact-title')).toHaveText('Soft rooftop landing');
  await expect(page.locator('#contact-detail')).toContainText('m/s');
  await expect(page.locator('#speed-note')).toHaveText('Landed on rooftop');
  await expect(page.locator('#toast')).toContainText('Soft rooftop landing');
  const landedAltitude = parseFloat(await page.locator('#altitude').innerText());
  expect(landedAltitude).toBeGreaterThan(rooftopHeight - 0.1);
  expect(landedAltitude).toBeLessThan(rooftopHeight + 0.2);
  await page.screenshot({ path: 'test-results/soft-rooftop-landing.png', fullPage: true });
  await page.getByRole('button', { name: 'Stop motors' }).click();
  await expect(page.locator('#flight-state-label')).toHaveText('SOFT LANDING · ROOFTOP');
  await page.getByRole('button', { name: 'Start motors' }).click();
  await page.keyboard.down('w');
  await expect.poll(async () => parseFloat(await page.locator('#altitude').innerText()), { intervals: [100] }).toBeGreaterThan(landedAltitude + 2);
  await page.keyboard.up('w');
  await expect(page.locator('#flight-state-label')).toContainText('IN FLIGHT');
  await expect(page.locator('#landing-feedback')).toBeHidden();
  expect(errors).toEqual([]);
});
